### PR TITLE
Merge staging into Master

### PR DESCRIPTION
**Pull request by kjacobsen16**

### CODE REVIEW

**Review by jknewson — COMMENTED** [review]
Is this ready to go to production? Last thing I remember is that they were still reviewing.

**Comment by kjacobsen16** [comment]
Oh, I didn't think there was a production, I just thought master should reflect what's on 500ss.

If not, then we can close this. The main thing is we need to make sure we move everything from  https://cida.usgs.gov/nldi/ to https://labs.waterdata.usgs.gov/api/nldi/linked-data/.

**Comment by jknewson** [comment]
oh, OK, that is fine, If we are defining 500ss as the 'prod' release server, then I'm good with marking as done

**Review by jknewson — APPROVED** [review]
ok, marking as approved, since this is the code on vm500ss

**Pull request merged**
